### ISSUE TITLE
"Go to definition" doesn't always work

### ISSUE THREAD

**Issue by mindplay-dk** [evanw/skew-vscode#1]
I opened the `src` folder of the Skew source project to see how well the VS code extension works now - I tried introducing a bunch of different kinds of errors, and it works really well, catches and reports every error in a helpful manner, auto-completion works well, and navigating around the codebase. Awesome! :-)

There are some minor hiccups with navigation though, and I can't seem to pinpoint any pattern, but sometimes it doesn't work.

For example, I open `backend/javascript.sk` and try CTRL-click on the reference to `SourceMapGenerator` in line 93, and I get an error:

    Unable to open 'sourcemap.sk': File not found (\\c:\workspace\test\skew\src\backend\sourcemap.sk).

Apart from the filename formatting being a little odd (`\\c:\`, I'm on Windows) that path is precisely the path to the file I'd expect it to open.

Oddly, if I manually open the file myself, leave it open, and *then* CTRL-click on the same reference, is does navigate to the correct file and line - so it seems this is a problem with opening the file, and not with determining which file/line to open?

**Comment by evanw** [comment]
7879459c0402876841f7f1b9ed1a11784e0039fe fixes this issue for me.
