### ISSUE TITLE
Extension crashes when there's a symlink in the project directory that links outside of the project directory

### ISSUE THREAD

**Issue by ryankaplan** [evanw/skew-vscode#5]
HI EVAN I MISS YOU!!

When I use this extension in a project directory that contains a symlink to a folder outside of the directory, it crashes with the following error.

skew: Error: ENOENT: no such file or directory, stat <path to symlink> at fs.statSync (fs.js:953:3) at Object.fs.statSync (ELECTRON_ASAR.js:295:16) at findAllFiles (/Users/.../.vscode/extensions/evanw.skew-vscode-0.7.42/out/server.js:260:16) at gatherInputs (/Users/.../.vscode/extensions/evanw.skew-vscode-0.7.42/out/server.js:286:32) at build (/Users/.../.vscode/extensions/evanw.skew-vscode-0.7.42/out/server.js:302:60) at /Users/.../.vscode/extensions/evanw.skew-vscode-0.7.42/out/server.js:363:27 at reportErrorsFromServer (/Users/.../.vscode/extensions/evanw.skew-vscode-0.7.42/out/server.js:238:7) at Timeout._onTimeout (/Users/.../.vscode/extensions/evanw.skew-vscode-0.7.42/out/server.js:362:7) at ontimeout (timers.js:427:11) at tryOnTimeout (timers.js:289:5)

I'd be ok with it following or not following the symlink, with a slight preference toward the latter :-)

**Comment by evanw** [comment]
Aww, I miss you too!

I think this was already fixed? Matthew filed this as #4 earlier. From the stack trace, it looks like you're on version 0.7.42 but the latest version is 0.7.50. Have you tried updating to the latest version?

**Comment by ryankaplan** [comment]
Haha, whoops. I looked through open issues and didn’t see this, so I figured that it hadn’t been filed. But it’s already fixed! Thanks!!

**Comment by ryankaplan** [comment]
@evanw when I install the extension through VSCode, the version I get is 0.7.49. Do you need to do something to update it to 0.7.50? This is what I see...

![Screen Shot 2020-07-21 at 2 02 57 PM](https://user-images.githubusercontent.com/945937/88106776-e2282b80-cb5a-11ea-90dc-11fc33a2af93.png)

**Comment by evanw** [comment]
I remember something screwy happening when I published this last time, but I forget what it was. At that time I was still able to install 0.7.50 locally so I figured it was ok. I can try publishing another version though.

Edit: Published as 0.7.51.

**Comment by ryankaplan** [comment]
@evanw it worked! Thanks!!
